### ISSUE TITLE
Markbot Problems

### ISSUE THREAD

**Issue by hovski** [hovski/animal-rescue-website#2]
@hellachella

I have the website completed and I've even had to downgrade the aesthetics to pass it through markbot - but with zero luck. I keep getting a bunch of the same errors across all the pages with no idea how to solve them. I've tried everything I can think of with no luck.

I'm hoping maybe you can help.
Markbot Issue: 
[https://imgur.com/a/jFfSTPj](url)

**Comment by hellachella** [comment]
Are you able to come see me on Monday? I will be available in N210 from 10-12.
